name: Run pytest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Diff Functions
        id: diff_functions
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            mjai/**/*.py
            tests/**/*.py

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build wheels
        uses: PyO3/maturin-action@v1
        with:
          target: ${{ matrix.target }}
          args: --release --out dist --interpreter python3.10
          sccache: "true"
          manylinux: auto

      - name: Install wheel package
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest mock
          python -m pip install ./dist/mjai-*-cp310-*.whl

      - name: Test with pytest
        run: |
          python -m pytest tests
        env:
          SKIP_TEST_WITH_DOCKER: false
